/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Hidden: typeof import('./src/components/hidden/hidden.vue')['default']
    Notice: typeof import('./src/components/notice/notice.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterTab: typeof import('./src/components/router-tab/router-tab.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TypeTab: typeof import('./src/components/type-tab/type-tab.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}
