export enum EventType {
  DANGER_PAGE_REFRESH = 'DANGER_PAGE_REFRESH',
  NOTICE_REFRESH = 'NOTICE_REFRESH',
  DANGER_DETAIL_REFRESH = 'DANGER_DETAIL_REFRESH',
  // 刷新三方施工详情页面
  THIRD_BUILD_REFRESH = 'THIRD_BUILD_REFRESH',
}