export enum EventType {
  // 展示隐患详情
  SHOW_HIDANGER_DETAIL = 'SHOW_HIDANGER_DETAIL',
  // 创建安全检查
  CREATE_SAFE_CHECK = 'CREATE_SAFE_CHECK',
  // 新建安全检查,选中的检查对象
  SELECTED_TARGET = 'SELECTED_TARGET',
  CREATE_TARGET = 'CREATE_TARGET',
  // 刷新检查列表
  REFRESH_PAGE = 'REFRESH_PAGE',
}